### ISSUE TITLE
www watchdog process

### ISSUE THREAD

**Issue by fmadio** [fmadio/public#132]
sometimes the www processes get stuck / hung due to various reasons. this means all http backend processing stops even tho the www process`s are up.

include a watchdog to check each www process is generating correct responses. if no repsonse (or connect) then kill the process and wait for the respawn

**Comment by fmadio** [comment]
the weird nginx timout problem is related to this. beleive libgcgi is getting stuck and not accepting new connections. likely to occour with a high uptime. Need to add a 100M http request soaktest to the regression suite to attempt reproduce the issue.

the watchdog process will also be helpful as a backup to clear the error

**Comment by fmadio** [comment]
strack trace from www_fcgibackend stalling

(gdb) bt
#0  0x00007fc4f38eac90 in read () from /lib/libc.so.6
#1  0x0000000000453ee9 in OS_Read (fd=<optimized out>, buf=<optimized out>, len=<optimized out>) at os_unix.c:460
#2  0x00000000004519fb in FillBuffProc (stream=<optimized out>) at fcgiapp.c:1636
#3  0x000000000045351f in FCGX_Accept_r (reqDataPtr=0x87ca40 <the_request>) at fcgiapp.c:2209
#4  0x00000000004536b3 in FCGX_Accept (in=in@entry=0x66c9b8 <in>, out=out@entry=0x66c9a0 <out>, err=err@entry=0x66c9c0 <err>, envp=envp@entry=0x66c9b0 <env>) at fcgiapp.c:2142
#5  0x000000000040704d in fcgi_accept (L=0x401f7378) at fFastCGI.c:31
#6  0x000000000041e3a9 in lj_BC_FUNCC ()
#7  0x000000000040da70 in lua_pcall ()

ends up with a bunch of FIN1 states

tcp        0    568 127.0.0.1:33582         127.0.0.1:9000          ESTABLISHED
tcp        0    193 127.0.0.1:33586         127.0.0.1:9000          FIN_WAIT1
tcp        0      0 127.0.0.1:9000          127.0.0.1:33520         ESTABLISHED
tcp        0      0 127.0.0.1:39637         127.0.0.1:80            TIME_WAIT
tcp        0      0 127.0.0.1:39640         127.0.0.1:80            TIME_WAIT

**Comment by fmadio** [comment]
issue occured after uploading a FW, likely memory/swap related issue. e.g libfcgi not handling out of memory or slow memory allocation of some description

**Comment by fmadio** [comment]
leave this for now. if anything update cron so it runs a bit more often
